name: Databricks Repo Actions

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  repo_interaction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Databricks CLI
        run: pip install --upgrade databricks-cli

      - name: Configure Databricks CLI
        run: |
           pip install pytest setuptools wheel


     

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
