name: Databricks Repo Actions

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  repo_interaction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --host https://adb-918245509424201.1.azuredatabricks.net --token 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

      - name: List Repo Contents (Example)
        run: |
          databricks workspace ls /Repos/Users/${{ secrets.DATABRICKS_USER }}/my_repo

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
